apiVersion: v1
kind: Service
metadata:
  name: oai-cu-svc
spec:
  selector:
    app: oai-cu
  clusterIP: None
  ports:
    - name: upf
      protocol: UDP #SCTP #TCP
      port: 2152
    - name: du1
      protocol: TCP
      port: 600
    - name: du2
      protocol: TCP
      port: 601
    - name: sctp
      protocol: SCTP
      port: 38412
    - name: f1
      protocol: SCTP
      port: 30923
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-cu-deployment
spec:
  selector:
    matchLabels:
      app: oai-cu
  replicas: 1
  template:
    metadata:
      labels:
        app: oai-cu
      annotations:
        k8s.v1.cni.cncf.io/networks: dual-flannel
    spec:
      containers:
      - name: myapp-container
        image: alan0415/oai-gnb:v0.2
        securityContext:
          privileged: true
        command: ["/bin/bash"]
        args: ["-c", "./setup-cu && sleep 3 && cd openairinterface5g/cmake_targets/ran_build/build && ./nr-softmodem --rfsim --sa -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/cu_gnb.conf"]
