apiVersion: v1
kind: Service
metadata:
  name: oai-du-svc
spec:
  selector:
    app: oai-du
  clusterIP: None
  ports:
    - name: upf
      protocol: UDP #SCTP #TCP
      port: 2152
    - name: test
      protocol: SCTP
      port: 2153
    - name: interconnection1
      protocol: TCP
      port: 600
    - name: interconnection2
      protocol: TCP
      port: 601
    - name: f1
      protocol: SCTP
      port: 30923 # 38472 on spec
---
apiVersion: v1
kind: Service
metadata:
  name: oai-ru-svc
spec:
  type: NodePort
  selector:
    app: oai-du
  ports:
    - name: rf
      protocol: TCP
      port: 4043
      targetPort: 4043
      nodePort: 30043
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-du-deployment
spec:
  selector:
    matchLabels:
      app: oai-du
  replicas: 1
  template:
    metadata:
      labels:
        app: oai-du
    spec:
      containers:
      - name: myapp-container
        image: alan0415/oai-gnb:v0.3
        securityContext:
          privileged: true
        command: ["/bin/bash"]
        args: ["-c", "sleep 30 && ./setup-du && cd openairinterface5g/cmake_targets/ran_build/build && ./nr-softmodem --rfsim --sa -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/du_gnb.conf"]
