apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dual-flannel
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "cni0",
    "ipam": {
      "type": "host-local",
      "subnet": "10.244.0.0/24",
      "rangeStart": "10.244.0.201",
      "rangeEnd": "10.244.0.210"
    }
  }'
